/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppServiceTeamsRouteImport } from './routes/_app.service-teams'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as AppServiceTeamsIdRouteImport } from './routes/_app.service-teams_.$id'
import { Route as AppSettingsMemberSettingsRouteImport } from './routes/_app.settings.member-settings'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app.settings.organization'
import { Route as AppTicketsIdRouteImport } from './routes/_app.tickets_.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceTeamsRoute = AppServiceTeamsRouteImport.update({
  id: '/service-teams',
  path: '/service-teams',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const AppServiceTeamsIdRoute = AppServiceTeamsIdRouteImport.update({
  id: '/service-teams_/$id',
  path: '/service-teams/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMemberSettingsRoute =
  AppSettingsMemberSettingsRouteImport.update({
    id: '/member-settings',
    path: '/member-settings',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTicketsIdRoute = AppTicketsIdRouteImport.update({
  id: '/tickets_/$id',
  path: '/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/overview': typeof AppOverviewRoute
  '/service-teams': typeof AppServiceTeamsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tickets': typeof AppTicketsRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/service-teams/$id': typeof AppServiceTeamsIdRoute
  '/settings/member-settings': typeof AppSettingsMemberSettingsRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/tickets/$id': typeof AppTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/overview': typeof AppOverviewRoute
  '/service-teams': typeof AppServiceTeamsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tickets': typeof AppTicketsRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/service-teams/$id': typeof AppServiceTeamsIdRoute
  '/settings/member-settings': typeof AppSettingsMemberSettingsRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/tickets/$id': typeof AppTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/overview': typeof AppOverviewRoute
  '/_app/service-teams': typeof AppServiceTeamsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tickets': typeof AppTicketsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/service-teams_/$id': typeof AppServiceTeamsIdRoute
  '/_app/settings/member-settings': typeof AppSettingsMemberSettingsRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/tickets_/$id': typeof AppTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/service-teams'
    | '/services'
    | '/settings'
    | '/tickets'
    | '/login'
    | '/register'
    | '/service-teams/$id'
    | '/settings/member-settings'
    | '/settings/organization'
    | '/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/service-teams'
    | '/services'
    | '/settings'
    | '/tickets'
    | '/login'
    | '/register'
    | '/service-teams/$id'
    | '/settings/member-settings'
    | '/settings/organization'
    | '/tickets/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/overview'
    | '/_app/service-teams'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/tickets'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_app/service-teams_/$id'
    | '/_app/settings/member-settings'
    | '/_app/settings/organization'
    | '/_app/tickets_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service-teams': {
      id: '/_app/service-teams'
      path: '/service-teams'
      fullPath: '/service-teams'
      preLoaderRoute: typeof AppServiceTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/service-teams_/$id': {
      id: '/_app/service-teams_/$id'
      path: '/service-teams/$id'
      fullPath: '/service-teams/$id'
      preLoaderRoute: typeof AppServiceTeamsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/member-settings': {
      id: '/_app/settings/member-settings'
      path: '/member-settings'
      fullPath: '/settings/member-settings'
      preLoaderRoute: typeof AppSettingsMemberSettingsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/tickets_/$id': {
      id: '/_app/tickets_/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AppTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsMemberSettingsRoute: typeof AppSettingsMemberSettingsRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsMemberSettingsRoute: AppSettingsMemberSettingsRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppOverviewRoute: typeof AppOverviewRoute
  AppServiceTeamsRoute: typeof AppServiceTeamsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTicketsRoute: typeof AppTicketsRoute
  AppServiceTeamsIdRoute: typeof AppServiceTeamsIdRoute
  AppTicketsIdRoute: typeof AppTicketsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOverviewRoute: AppOverviewRoute,
  AppServiceTeamsRoute: AppServiceTeamsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTicketsRoute: AppTicketsRoute,
  AppServiceTeamsIdRoute: AppServiceTeamsIdRoute,
  AppTicketsIdRoute: AppTicketsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
