name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Detect changed files
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            backend:
              - 'server/**'
              - '.github/workflows/ci.yml'
            
            frontend:
              - 'client/**'
              - '.github/workflows/ci.yml'
  backend-ci:
    needs: changes
    if: needs.changes.outputs.backend == 'true'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
          cache-dependency-path: server/pom.xml

      - name: Run backend tests
        run: ./mvnw test

  frontend-ci:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build frontend
        run: npm run build


